services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env  # Load environment variables from .env file

  frontend:
    build: ./dance
    ports:
      - "3000:3000"

